# Generated by Django 5.1.3 on 2024-12-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubecifrada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivoscompartidos',
            name='path_archivo',
        ),
        migrations.AddField(
            model_name='archivoscompartidos',
            name='archivo_cifrado',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
