# Generated by Django 5.1.3 on 2024-12-09 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubecifrada', '0002_remove_archivoscompartidos_path_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocompartido',
            name='public_key',
        ),
        migrations.AddField(
            model_name='archivoscompartidos',
            name='nombre_archivo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archivoscompartidos',
            name='uuid_user_subidor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrantesgrupo',
            name='llave_maestra_cifrada',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='integrantesgrupo',
            name='uuid_user_invitador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='llave_publica',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
