# Generated by Django 5.1.3 on 2024-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubecifrada', '0003_remove_grupocompartido_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantesgrupo',
            name='llave_maestra_cifrada',
            field=models.BinaryField(default=b''),
        ),
    ]
