# Generated by Django 5.1.3 on 2024-12-06 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCompartido',
            fields=[
                ('uuid_grupo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_grupo', models.CharField(max_length=255, unique=True)),
                ('uuid_user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosCompartidos',
            fields=[
                ('uuid_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('path_archivo', models.CharField(max_length=255)),
                ('uuid_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='users.grupocompartido')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrantesGrupo',
            fields=[
                ('uuid_integrantes', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='users.grupocompartido')),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
