# Generated by Django 5.1.3 on 2024-12-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_grupocompartido_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocompartido',
            name='uuid_grupo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
