# Generated by Django 5.1.3 on 2024-12-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_grupocompartido_uuid_grupo'),
    ]

    operations = [
    ]
