# Generated by Django 5.1.3 on 2024-12-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241208_0223'),
    ]

    operations = [
    ]
